### ISSUE TITLE
Calculation page is too large

### ISSUE THREAD

**Issue by credo99** [jonvitale/SenseColorableSankey#2]
Hi, in a chart with one dimension and 1 measure and only 40 entries in QSense version February 2018 why would this error come? Thanks
The bar chart for this visualization is very simple

![snap 2018-04-18 at 17 58 45](https://user-images.githubusercontent.com/6890477/38940192-411f3cf4-4332-11e8-84dc-79ef9f3bf835.jpg)

**Comment by jonvitale** [comment]
Credo,

Take a look at the other issue about tutorials, that somehow became about this.
https://github.com/jonvitale/SenseColorableSankey/issues/1

Basically, I made one simple change to make it work (updating qHeight). I forgot to commit my changes, but I just did it (v0.4.2). So you can try downloading the new version and replacing. Make sure to delete any old Sankey objects in your app or it will probably show the same error.

Alternatively, you can make the change in the version you are currently using. I basically changed one number "qHeight".

**Comment by credo99** [comment]
Hi, thanks for the info, I reloaded the new version, right now it's not complaining about the calculation size but I get the same error of Incomplete visualization that I get also with the Xavier or Parkman extensions. I did the Disable cache trick, did F5 but still bugging me.
![snap 2018-04-18 at 19 32 41](https://user-images.githubusercontent.com/6890477/38945467-41e17e38-433f-11e8-8e59-867159e4ceab.jpg)
I think it's because I have the latest version of QSense, maybe the API changed for extensions somehow.

**Comment by jonvitale** [comment]
Just to make sure: delete the visualization, reload, try adding it again.
If this is Desktop try closing it and opening it again.

If that's not working can you open the developer tools and see if there is
an error, then post it.

If you are using desktop you can click ctrl-shift-rightclick and it will
allow you to open the dev tools.

**Comment by credo99** [comment]
I did it, can't see any upfront errors. Where should I look in the dev tools for errors. It seems all the .js files are correct found and loaded. It shows also the last version of your js is loaded 
![snap 2018-04-18 at 19 58 17](https://user-images.githubusercontent.com/6890477/38946723-0910105c-4343-11e8-9ec5-e7a29aa06606.jpg)
![snap 2018-04-18 at 19 54 55](https://user-images.githubusercontent.com/6890477/38946724-092ae44a-4343-11e8-8c16-db0716f60531.jpg)
![snap 2018-04-18 at 19 53 50](https://user-images.githubusercontent.com/6890477/38946725-09461ca6-4343-11e8-8a54-19e4ba7105d0.jpg)

**Comment by jonvitale** [comment]
Go to "Console", make sure you have it open as the page loads to see if it
shoots an error.

**Comment by credo99** [comment]
No error, just this line:

Navigated to http://localhost:4848/sense/app/C%3A%5CUsers%5Cradu.bengulescu%5CDocuments%…-8b1e-4285-85dd-d1abae04d120/state/analysis/feature/desktop_authentication

**Comment by credo99** [comment]
I get this error though, but not in the console

Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Comment by jonvitale** [comment]
This really sounds like a weird browser issue that some amount of
refreshing-closing-clearing cache will fix, but if you'd like me to try it
on my own system upload the qlik app.

**Comment by credo99** [comment]
I'll give it a try on another computer at home and see if it's browser or LAN-based-security related. Thanks for the assistance.

**Comment by credo99** [comment]
I tried the extension on the SalesDiscovery sample from inside the standard QlikSense installation (february 2018 version) and both on Firefox and Chrome (using http://localhost:4848/hub) gave the same error of Incomplete visualization. I think you can replicate it also by installing this version. What is your Sense version on which the extension works? Thanks

**Comment by credo99** [comment]
Update! I was using only one dimension. As long as I entered two dimensions it worked.

**Comment by jonvitale** [comment]
ha, yes, it is certainly incomplete with two dimensions. Have fun.
