### ISSUE TITLE
Incorrect import of the qlik module

### ISSUE THREAD

**Issue by mindspank** [jonvitale/SenseColorableSankey#5]
Hey,
this project incorrectly imports the `qlik` module via `js/qlik` which will fail to render in June 2018.
Please change `js/qlik` to `qlik` as per documentation at https://help.qlik.com/en-US/sense-developer/April2018/Subsystems/Extensions/Content/Howtos/call-qlik-library.htm

**Comment by jonvitale** [comment]
Thanks for the heads up.
